# Generated by Django 4.2 on 2024-05-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_auth',
            field=models.BooleanField(default=False),
        ),
    ]
