# Generated by Django 4.2 on 2024-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code_authentication_app', '0003_alter_profile_qr_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_auth',
            field=models.BooleanField(default=False),
        ),
    ]
